url_pfx: docs.google.com/spreadsheets/d/
url_roosters: 1zt4xR9non3vIus4A9gVvk15HTMAunPBGywMOtAMI-0U
url_wordpress_gidsinfo: 16DrvLEXi3mEa9AbSw28YBkYpCvyO1wXwBwaNi7HpBkA

modelrooster_versie: "20250417"
