url_pfx: docs.google.com/spreadsheets/d/
url_roosters: 1zt4xR9non3vIus4A9gVvk15HTMAunPBGywMOtAMI-0U
url_wordpress_gidsinfo: 16DrvLEXi3mEa9AbSw28YBkYpCvyO1wXwBwaNi7HpBkA
url_rooster_woj: 1LdBjK5hcpl8m1ZdcZujWWcsx7nLJPY8Gt69mjN8QS9A

modelrooster_versie: "20250417"
